# Generated by Django 4.1.7 on 2023-03-19 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quizsection", "0002_person_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="person",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="quizsection.person",
            ),
        ),
    ]
